[build]
  base = "trackit"          # The folder containing package.json
  command = "npm run build"
  publish = ".next"         # This is relative to the base directory

[build.environment]
  NEXT_PRIVATE_TARGET = "server"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404